public class MuchBetter {
    public static void main(String[] args) {
        System.out.println("A \"quoted\" String is 'much' better if you lean\n the rules of \"excape sequences.\"\n Also, \"\" represents an empty String.\n Don't forget: use \" instead of \" !\n '' is not the same as \" ");
                //The slash n is like breaking it into a new line. and slash quote is making a quotation mark
        );

    }
}
